# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Beillen' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Masonry'
  pod 'YYCategories'
  pod 'PAPreferences'
  pod 'YYModel'
  pod 'MBProgressHUD'
  pod 'ReactiveObjC'
  # Pods for Beillen

  target 'BeillenTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BeillenUITests' do
    # Pods for testing
  end

end
